### ISSUE TITLE
Adaption to high-dimentional input such as 3d input

### ISSUE THREAD

**Issue by trannguyenle95** [wjmaddox/online_gp#4]
Hi,

I have been trying to adapt our code to 3d input but so far failed to do so. Is it possible to give hints regarding this matter? Thanks a lot!

**Comment by cagoc** [comment]
Hi,
Sorry to bother you. I have been trying to reproduce `active_learning.py` with wiski model but I failed. it is said that 

> `Traceback (most recent call last):
  File "C:\code\online_vargp-main\experiments\active_learning\qnIPV_experiment.py", line 308, in <module>
    main(args)
  File "C:\code\online_vargp-main\experiments\active_learning\qnIPV_experiment.py", line 146, in main
    mll = mll_type(model.likelihood, model, **mll_kwargs)
                   ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'likelihood'
`
I have tried to use `ExactMarginalLogLikelihood` and `BatchedWoodburyMarginalLogLikelihood` but none of them succeeded. Have you reproduce `active_learning.py` with wiski model successfully? Thanks a lot!
